export const emissionFactors = {
  materials: [
    { name: "Acier (Recyclé)", factor: 0.5, unit: "kg CO2e/kg" },
    { name: "Acier (Vierge)", factor: 2.0, unit: "kg CO2e/kg" },
    { name: "Aluminium (Recyclé)", factor: 1.5, unit: "kg CO2e/kg" },
    { name: "Aluminium (Vierge)", factor: 11.0, unit: "kg CO2e/kg" },
    { name: "Plastique (PET)", factor: 2.3, unit: "kg CO2e/kg" },
    { name: "Verre", factor: 0.9, unit: "kg CO2e/kg" },
    { name: "Papier/Carton", factor: 0.6, unit: "kg CO2e/kg" },
    { name: "Béton", factor: 0, unit: "kg CO2e/m³" }, // Le calcul est maintenant dynamique
    { name: "Bois (Source durable)", factor: 0.05, unit: "kg CO2e/kg" },
    { name: "Canalisation PVC", factor: 2.47, unit: "kg CO2e/kg" },
    { name: "Barre d'acier", factor: 2.21, unit: "kg CO2e/kg" },
    { name: "Cuivre Classique", factor: 4.50, unit: "kg CO2e/kg" },
    { name: "Cuivre recyclé", factor: 1.50, unit: "kg CO2e/kg" },
  ],
  concrete: [
    // Facteurs d'émission pour 1 tonne de ciment. Unité: tCO2eq/t de ciment
    { name: "CEM I (ATILH)", factor: 0.752, unit: "tCO₂eq/t" },
    { name: "CEM II/A-LL ou LL (ATILH)", factor: 0.640, unit: "tCO₂eq/t" },
    { name: "CEM II/A-S A-M et A-V (ATILH)", factor: 0.619, unit: "tCO₂eq/t" },
    { name: "CEM II/B-L ou LL (ATILH)", factor: 0.547, unit: "tCO₂eq/t" },
    { name: "CEM II/B-M CEM II/B-S (ATILH)", factor: 0.554, unit: "tCO₂eq/t" },
    { name: "CEM III/A (ATILH)", factor: 0.467, unit: "tCO₂eq/t" },
    { name: "CEM III/A PM et ES (ATILH)", factor: 0.334, unit: "tCO₂eq/t" },
    { name: "CEM III/B (ATILH)", factor: 0.316, unit: "tCO₂eq/t" },
    { name: "CEM III/C (ATILH)", factor: 0.199, unit: "tCO₂eq/t" },
    { name: "CEM V/A (S-V) (ATILH)", factor: 0.479, unit: "tCO₂eq/t" },
    { name: "CEM VI (ECOCEM)", factor: 0.417, unit: "tCO₂eq/t" },
  ],
  rebar: [
    { name: "0.7 kgCO₂eq/kg", factor: 0.7 },
    { name: "0.8 kgCO₂eq/kg", factor: 0.8 },
    { name: "0.9 kgCO₂eq/kg", factor: 0.9 },
    { name: "1.0 kgCO₂eq/kg", factor: 1.0 },
    { name: "1.1 kgCO₂eq/kg", factor: 1.1 },
    { name: "1.2 kgCO₂eq/kg (Classique)", factor: 1.2 },
    { name: "1.3 kgCO₂eq/kg", factor: 1.3 },
    { name: "1.4 kgCO₂eq/kg", factor: 1.4 },
    { name: "1.5 kgCO₂eq/kg", factor: 1.5 },
    { name: "1.6 kgCO₂eq/kg", factor: 1.6 },
    { name: "1.7 kgCO₂eq/kg", factor: 1.7 },
    { name: "1.8 kgCO₂eq/kg", factor: 1.8 },
    { name: "1.9 kgCO₂eq/kg", factor: 1.9 },
    { name: "2.0 kgCO₂eq/kg", factor: 2.0 },
  ],
  manufacturing: [
    { name: "Usinage", factor: 5.0, unit: "kg CO2e/hr" },
    { name: "Soudage", factor: 0.26, unit: "kg CO2e/hr" },
    { name: "Peinture", factor: 3.65, unit: "kg CO2e/hr" },
    { name: "Impression 3D (Plastique)", factor: 0.01, unit: "kg CO2e/hr" },
  ],
  implementation: [
    { name: "Grue", factor: 13.5, unit: "kg CO2e/hr" },
    { name: "Bétonnière", factor: 8.5, unit: "kg CO2e/hr" },
    { name: "Groupe électrogène", factor: 10.5, unit: "kg CO2e/hr" },
    { name: "Pelleuteuse", factor: 20.0, unit: "kg CO2e/hr" },
    { name: "Pelle araignée", factor: 14.5, unit: "kg CO2e/hr" },
    { name: "Compacteur", factor: 18.0, unit: "kg CO2e/hr" },
    { name: "Bulldozer", factor: 27.5, unit: "kg CO2e/hr" },
    { name: "Chargeuse", factor: 14.0, unit: "kg CO2e/hr" },
    { name: "Marteau piqueur électrique (P : 2100 W)", factor: 0.11, unit: "kg CO2e/hr" },
    { name: "Marteau piqueur pneumatique", factor: 15.80, unit: "kg CO2e/hr" },
    { name: "Foreuse (1500 W)", factor: 0.04, unit: "kg CO2e/hr" },
  ],
  transport: [
    { name: "Route (Camion diesel)", factor: 0.1, unit: "kg CO2e/t-km" },
    { name: "Route (Camion électrique)", factor: 0.04, unit: "kg CO2e/t-km" },
    { name: "Rail", factor: 0.02, unit: "kg CO2e/t-km" },
    { name: "Mer", factor: 0.01, unit: "kg CO2e/t-km" },
    { name: "Air", factor: 0.6, unit: "kg CO2e/t-km" },
    { name: "Hélicoptère Airbus H125", factor: 1.77, unit: "kg CO2e/t-km" },
    { name: "Hélicoptère Bell 206 JetRanger", factor: 1.12, unit: "kg CO2e/t-km" },
    { name: "Hélicoptère Robinson R44", factor: 0.67, unit: "kg CO2e/t-km" },
  ],
  endOfLife: [
    { name: "Mise en décharge", factor: 0.2, unit: "kg CO2e/kg" },
    { name: "Incinération", factor: 1.0, unit: "kg CO2e/kg" },
    { name: "Recyclage (Métaux)", factor: -1.8, unit: "kg CO2e/kg" },
    { name: "Recyclage (Plastiques)", factor: -1.2, unit: "kg CO2e/kg" },
    { name: "Compostage", factor: -0.1, unit: "kg CO2e/kg" },
  ],
};

export type EmissionFactors = typeof emissionFactors;
